#!/usr/bin/env node
// THE DESIGNER-FACING NAMING TABLES ARE GENERATED FROM THE RECIPES, AND THIS IS WHAT KEEPS THEM SO.
//
//   node scripts/behaviour-docs.mjs --check    # part of `npm run build`
//   node scripts/behaviour-docs.mjs --write    # rewrite the generated blocks in place
//
// docs/SVG_AUTHORING.md §5b tells a designer what to name their layers so a behaviour arrives
// bound. On 2026-09-05 that page said `Answer 1` worked for a live vote and it did not
// (docs/backlog/answer-n-is-documented-as-a-vote-row-word-but-always-reads-as-a-quiz.md): the page
// was prose, the matcher was code, and nothing held the two together. Now the words live once, in
// src/templates/behaviours/words.json, the recipes and the proposal read them from there, and this
// script writes the tables between `<!-- behaviour:<id>:start -->` / `:end -->` markers on that
// page and refuses a build where the committed page disagrees.
//
// It also checks the words against THEMSELVES: every example name the page prints (`teach`, and
// every synonym in `also`) must match its role through the same tokenizer the proposal uses - a
// plain-JS twin of `rowTokenOf` in src/templates/behaviours/naming.ts, kept in step by hand. A name
// the docs teach that the matcher would not read is the exact defect above, caught before it is
// published.
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('../', import.meta.url));
const WORDS = resolve(ROOT, 'src/templates/behaviours/words.json');
const PAGE = resolve(ROOT, 'docs/SVG_AUTHORING.md');

/** naming.ts `rowTokenOf`, in plain JS: the one key token (a letter or a number) and the head. */
export function rowTokenOf(label) {
  const tokens = label.trim().split(/[\s_-]+/).filter(Boolean);
  const keys = tokens.filter((t) => /^(?:[A-Za-z]|\d+)$/.test(t));
  if (keys.length !== 1) return { key: null, head: label.trim() };
  return { key: keys[0].toUpperCase(), head: tokens.filter((t) => t !== keys[0]).join(' ') };
}

/** naming.ts `matchRole`, on the JSON shape. */
export function matchesRole(role, label) {
  const words = new RegExp(role.words, 'i');
  const weak = role.weak ? new RegExp(role.weak, 'i') : null;
  const { key, head } = rowTokenOf(label);
  if (role.perRow) {
    if (key === null) return false;
    return words.test(head) || (weak ? weak.test(head) : false);
  }
  return words.test(label) || (weak ? weak.test(label) : false);
}

const escapeCell = (text) => text.replace(/\|/g, '\\|');

/** The generated block for one recipe: the table, the row bounds, the synonyms. */
export function blockFor(id, entry) {
  const lines = ['| Layer | Name it | What it is |', '|---|---|---|'];
  for (const role of entry.roles) {
    const name = role.countdown ? role.teach : `\`${role.teach}\``;
    const layer = role.perRow ? `${role.label.toLowerCase()} (one per row)` : role.label.toLowerCase();
    lines.push(`| ${escapeCell(layer)} | ${name} | ${escapeCell(role.what)} |`);
  }
  const synonyms = entry.roles
    .filter((r) => r.also && r.also.length > 0)
    .map((r) => `${r.also.map((a) => `\`${a}\``).join(', ')} ${r.also.length === 1 ? 'works' : 'work'} as well as \`${r.teach}\``);
  const tail = [];
  if (entry.rows) tail.push(entry.rows.teach);
  tail.push(`The operator gets ${entry.buttons}.`);
  const out = [`<!-- behaviour:${id}:start - generated by scripts/behaviour-docs.mjs from src/templates/behaviours/words.json; edit the JSON, then \`npm run write:behaviour-docs\` -->`, ...lines, ''];
  if (synonyms.length > 0) out.push(`${synonyms.join('; ')}.`, '');
  out.push(tail.join(' '), `<!-- behaviour:${id}:end -->`);
  return out.join('\n');
}

export function problems(words) {
  const out = [];
  for (const [id, entry] of Object.entries(words)) {
    if (id === '_') continue;
    for (const role of entry.roles) {
      if (role.countdown) continue;
      for (const name of [role.teach, ...(role.also ?? [])]) {
        if (!matchesRole(role, name)) out.push(`${id}/${role.id}: the docs teach "${name}", but the matcher would not read it as that role`);
      }
      if (role.perRow && rowTokenOf(role.teach).key === null) out.push(`${id}/${role.id}: "${role.teach}" is taught for a per-row role but carries no row key`);
    }
  }
  return out;
}

export function render(page, words) {
  let out = page;
  for (const [id, entry] of Object.entries(words)) {
    if (id === '_') continue;
    const re = new RegExp(`<!-- behaviour:${id}:start[^\\n]*-->[\\s\\S]*?<!-- behaviour:${id}:end -->`);
    if (!re.test(out)) throw new Error(`docs/SVG_AUTHORING.md has no <!-- behaviour:${id}:start --> … :end --> block to write into.`);
    out = out.replace(re, () => blockFor(id, entry));
  }
  return out;
}

function main() {
  const mode = process.argv.includes('--write') ? 'write' : 'check';
  const words = JSON.parse(readFileSync(WORDS, 'utf8'));
  const found = problems(words);
  if (found.length > 0) {
    console.error('behaviour-docs: the words disagree with themselves:');
    for (const line of found) console.error(`  - ${line}`);
    process.exit(1);
  }
  const page = readFileSync(PAGE, 'utf8');
  const rendered = render(page, words);
  if (mode === 'write') {
    if (rendered !== page) writeFileSync(PAGE, rendered);
    console.log(`behaviour-docs: ${rendered === page ? 'already current' : 'written'} - docs/SVG_AUTHORING.md`);
    return;
  }
  if (rendered !== page) {
    console.error('behaviour-docs: docs/SVG_AUTHORING.md §5b does not match src/templates/behaviours/words.json - run `npm run write:behaviour-docs` and commit the result.');
    process.exit(1);
  }
  console.log('behaviour-docs: docs/SVG_AUTHORING.md §5b matches words.json');
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
