#!/usr/bin/env node
// gate: build
// guards: src/templates/behaviours/**, docs/SVG_AUTHORING.md, docs.html
//
// THE DESIGNER-FACING NAMING TABLES ARE GENERATED FROM THE RECIPES, AND THIS IS WHAT KEEPS THEM SO.
//
//   node scripts/behaviour-docs.mjs --check    # part of `npm run build`
//   node scripts/behaviour-docs.mjs --write    # rewrite the generated blocks in place
//
// docs/SVG_AUTHORING.md §5b tells a designer what to name their layers so a behaviour arrives
// bound. On 2026-09-05 that page said `Answer 1` worked for a live vote and it did not
// (docs/backlog/answer-n-is-documented-as-a-vote-row-word-but-always-reads-as-a-quiz.md): the page
// was prose, the matcher was code, and nothing held the two together. Now the words live once, in
// src/templates/behaviours/words.json, the recipes and the proposal read them from there, and this
// script writes the tables between `<!-- behaviour:<id>:start -->` / `:end -->` markers on that
// page and refuses a build where the committed page disagrees.
//
// It also checks the words against THEMSELVES: every example name the page prints (`teach`, and
// every synonym in `also`) must match its role through the same tokenizer the proposal uses - a
// plain-JS twin of `rowTokenOf` in src/templates/behaviours/naming.ts, kept in step by hand. A name
// the docs teach that the matcher would not read is the exact defect above, caught before it is
// published.
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { measured } from './measured.mjs';

const ROOT = fileURLToPath(new URL('../', import.meta.url));
const WORDS = resolve(ROOT, 'src/templates/behaviours/words.json');
const PAGE = resolve(ROOT, 'docs/SVG_AUTHORING.md');
const PUBLIC = resolve(ROOT, 'docs.html');

/** naming.ts `rowTokenOf`, in plain JS: the one key token (a letter or a number) and the head. */
export function rowTokenOf(label) {
  const tokens = label.trim().split(/[\s_-]+/).filter(Boolean);
  const keys = tokens.filter((t) => /^(?:[A-Za-z]|\d+)$/.test(t));
  if (keys.length !== 1) return { key: null, head: label.trim() };
  return { key: keys[0].toUpperCase(), head: tokens.filter((t) => t !== keys[0]).join(' ') };
}

/** naming.ts `matchRole`, on the JSON shape. */
export function matchesRole(role, label) {
  const words = new RegExp(role.words, 'i');
  const weak = role.weak ? new RegExp(role.weak, 'i') : null;
  const { key, head } = rowTokenOf(label);
  if (role.perRow) {
    if (key === null) return false;
    return words.test(head) || (weak ? weak.test(head) : false);
  }
  return words.test(label) || (weak ? weak.test(label) : false);
}

const escapeCell = (text) => text.replace(/\|/g, '\\|');

/** The generated block for one recipe: the table, the row bounds, the synonyms. */
export function blockFor(id, entry) {
  const lines = ['| Layer | Name it | What it is |', '|---|---|---|'];
  for (const role of entry.roles) {
    const name = role.countdown ? role.teach : `\`${role.teach}\``;
    const layer = role.perRow ? `${role.label.toLowerCase()} (one per row)` : role.label.toLowerCase();
    lines.push(`| ${escapeCell(layer)} | ${name} | ${escapeCell(role.what)} |`);
  }
  const synonyms = entry.roles
    .filter((r) => r.also && r.also.length > 0)
    .map((r) => `${r.also.map((a) => `\`${a}\``).join(', ')} ${r.also.length === 1 ? 'works' : 'work'} as well as \`${r.teach}\``);
  const tail = [];
  if (entry.rows) tail.push(entry.rows.teach);
  tail.push(`The operator gets ${entry.buttons}.`);
  const out = [`<!-- behaviour:${id}:start - generated by scripts/behaviour-docs.mjs from src/templates/behaviours/words.json; edit the JSON, then \`npm run write:behaviour-docs\` -->`, ...lines, ''];
  if (synonyms.length > 0) out.push(`${synonyms.join('; ')}.`, '');
  out.push(tail.join(' '), `<!-- behaviour:${id}:end -->`);
  return out.join('\n');
}

export function problems(words) {
  const out = [];
  for (const [id, entry] of Object.entries(words)) {
    if (id === '_') continue;
    for (const role of entry.roles) {
      if (role.countdown) continue;
      for (const name of [role.teach, ...(role.also ?? [])]) {
        if (!matchesRole(role, name)) out.push(`${id}/${role.id}: the docs teach "${name}", but the matcher would not read it as that role`);
      }
      if (role.perRow && rowTokenOf(role.teach).key === null) out.push(`${id}/${role.id}: "${role.teach}" is taught for a per-row role but carries no row key`);
    }
  }
  return out;
}

export function render(page, words) {
  let out = page;
  for (const [id, entry] of Object.entries(words)) {
    if (id === '_') continue;
    const re = new RegExp(`<!-- behaviour:${id}:start[^\\n]*-->[\\s\\S]*?<!-- behaviour:${id}:end -->`);
    if (!re.test(out)) throw new Error(`docs/SVG_AUTHORING.md has no <!-- behaviour:${id}:start --> … :end --> block to write into.`);
    out = out.replace(re, () => blockFor(id, entry));
  }
  return out;
}

// THE PUBLIC PAGE CARRIES THE SAME WORDS. docs.html's "Layer names" page opens with the naming
// system and a table of every name the importer reads (docs/backlog/one-layer-naming-system-for-
// every-graphic.md): the taught spelling, the synonyms and what the layer does, for every
// behaviour. Written between one pair of markers by the same script, for the same reason as the
// authoring page: a student copies a name off the public docs, and a name the docs print that the
// matcher would not read is the defect this script exists to stop.

/** The type pages the public docs have, in the order the page lists them. A behaviour without a
 *  page is still in the table - the wizard offers it under What it does - just not linked. */
const PUBLIC_PAGES = { score: '#scoreboards', quiz: '#quiz', vote: '#svg-vote', countdown: '#countdowns' };

const escapeHtml = (text) => text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const code = (text) => `<code>${escapeHtml(text)}</code>`;
/** The JSON spells a label the way a picker prints it mid-sentence ("selected"); a table cell
 *  starts a line, so it starts with a capital. */
const capital = (text) => text.charAt(0).toUpperCase() + text.slice(1);

/** The rows of the public table for one behaviour: a heading row naming the type, one row per
 *  role, and the row-count sentence where the type has rows. */
export function publicRowsFor(id, entry) {
  const name = capital(entry.name.replace(/^The /, ''));
  const heading = PUBLIC_PAGES[id] ? `<a href="${PUBLIC_PAGES[id]}">${escapeHtml(name)}</a>` : escapeHtml(name);
  const lines = [`<tr class="doc-words-type"><th colspan="4">${heading}</th></tr>`];
  for (const role of entry.roles) {
    const layer = escapeHtml(capital(role.label)) + (role.perRow ? ' (one per row)' : '');
    const taught = role.countdown ? escapeHtml(role.teach) : code(role.teach);
    const also = (role.also ?? []).map(code).join(', ');
    lines.push(`<tr><td>${layer}</td><td>${taught}</td><td>${also}</td><td>${escapeHtml(role.what)}</td></tr>`);
  }
  if (entry.rows) lines.push(`<tr><td colspan="4" class="doc-words-rows">${escapeHtml(entry.rows.teach)}</td></tr>`);
  return lines.join('\n');
}

/** The whole public block: the types with a page first, in page order, then the rest. Joined
 *  with the page's own line ending: docs.html is checked out with CRLF on Windows, and a block
 *  written with bare newlines into it read as stale the next time an editor touched the file. */
export function publicBlock(words, eol = '\n') {
  const ids = Object.keys(words).filter((id) => id !== '_' && words[id].roles.length > 0);
  const paged = Object.keys(PUBLIC_PAGES).filter((id) => ids.includes(id));
  const ordered = [...paged, ...ids.filter((id) => !paged.includes(id))];
  return [
    '<!-- behaviour-words:start - generated by scripts/behaviour-docs.mjs from src/templates/behaviours/words.json; edit the JSON, then `npm run write:behaviour-docs` -->',
    '<div class="doc-table"><table class="doc-words">',
    '<tr><th>Layer</th><th>Name it</th><th>Also works</th><th>What it does</th></tr>',
    ...ordered.map((id) => publicRowsFor(id, words[id]).split('\n')).flat(),
    '</table></div>',
    '<!-- behaviour-words:end -->',
  ].join(eol);
}

export function renderPublic(page, words) {
  const re = /<!-- behaviour-words:start[^\n]*-->[\s\S]*?<!-- behaviour-words:end -->/;
  if (!re.test(page)) throw new Error('docs.html has no <!-- behaviour-words:start --> … :end --> block to write into.');
  const eol = page.includes('\r\n') ? '\r\n' : '\n';
  return page.replace(re, () => publicBlock(words, eol));
}

function main() {
  const mode = process.argv.includes('--write') ? 'write' : 'check';
  const words = JSON.parse(readFileSync(WORDS, 'utf8'));
  // `_` is the shared header of the JSON rather than a behaviour, so it is not one of the entries
  // this pins - the same exclusion `problems()` and `render()` make.
  measured(Object.keys(words).filter((id) => id !== '_').length, 'behaviour words');
  const found = problems(words);
  if (found.length > 0) {
    console.error('behaviour-docs: the words disagree with themselves:');
    for (const line of found) console.error(`  - ${line}`);
    process.exit(1);
  }
  const targets = [
    { file: PAGE, label: 'docs/SVG_AUTHORING.md §5b', render },
    { file: PUBLIC, label: 'docs.html #svg-layers', render: renderPublic },
  ];
  let stale = false;
  for (const target of targets) {
    const page = readFileSync(target.file, 'utf8');
    const rendered = target.render(page, words);
    if (mode === 'write') {
      if (rendered !== page) writeFileSync(target.file, rendered);
      console.log(`behaviour-docs: ${rendered === page ? 'already current' : 'written'} - ${target.label}`);
    } else if (rendered !== page) {
      console.error(`behaviour-docs: ${target.label} does not match src/templates/behaviours/words.json - run \`npm run write:behaviour-docs\` and commit the result.`);
      stale = true;
    } else {
      console.log(`behaviour-docs: ${target.label} matches words.json`);
    }
  }
  if (stale) process.exit(1);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
