// The rule store behind the compiled contracts (docs/WORKFLOW_ARCHITECTURE.md §5.3).
//
// One rule per file under contracts/rules/<area>/<slug>.md, one incident per file under
// contracts/records/<area>/<date>-<slug>.md. Nothing here is loaded into a session directly:
// scripts/compile-contracts.mjs turns the active rules into the path-scoped files under
// .claude/rules/ (loaded by Claude Code only when a matching file is read) and into
// contracts/index.md. scripts/learn.mjs is the write path. This module holds what both share:
// the file format, the validation, the symbol extraction, the near-duplicate measure and the
// renderer, so the two cannot disagree about what a rule is.
//
// Rule file shape:
//
//   ---
//   scope: src/components/wizard/**, src/templates/shared/base.ts
//   kind: trap            # invariant | trap | rule | taste
//   fires: contract       # contract | hook:<name> | gate:<script> | test:<spec path>
//   status: active        # active | retired
//   since: 2026-09-02
//   supersedes:           # comma-separated rule ids, optional
//   record: contracts/records/wizard/2026-09-02-inline-hidden-holder.md
//   ---
//   The rule, imperative, one to three sentences, symbols in backticks.
//
// The id is the path: <area>/<slug>. Rule text carries no dates, run ids or measurements - those
// belong in the record - because a rule that carries its own evidence is what turned the
// contracts into the 570 KB corpus measured on 2026-09-06.

import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs';
import path from 'node:path';

import { parseFrontmatter } from './owner-receipts.mjs';

export const RULES_DIR = 'contracts/rules';
export const RECORDS_DIR = 'contracts/records';
export const OUTPUT_DIR = '.claude/rules';
export const INDEX_PATH = 'contracts/index.md';

export const KINDS = ['invariant', 'trap', 'rule', 'taste'];
export const STATUSES = ['active', 'retired'];
/** Compile order inside one generated file, and the order the budget demotes from (last first). */
const KIND_PRIORITY = { invariant: 0, trap: 1, rule: 2, taste: 3 };

/**
 * Near-duplicate threshold on `similarity()`. Two active rules at or above it fail the compile:
 * one of them supersedes the other, or they are one rule. Calibrated on the empty store, so it
 * is a first guess; docs/WORKFLOW_ARCHITECTURE.md phase 2b re-measures it on the migrated corpus.
 */
export const DUPLICATE_THRESHOLD = 0.6;

/** What the body of a rule may not carry. Each pattern names what it catches for the message. */
export const EVIDENCE_PATTERNS = [
  { name: 'a date', regex: /\b20\d\d-\d\d-\d\d\b/ },
  { name: 'a run id', regex: /\b\d{9,}\b/ },
  { name: 'a measurement', regex: /\b\d[\d,.]*\s?(bytes|KB|MB|GB|ms|min|minutes|hours|%)\b/ },
];

const GENERATED_MARKER = 'GENERATED by scripts/compile-contracts.mjs';

/** Every `` `token` `` in a text, distinct, in order of first appearance. */
export function symbolsOf(text) {
  const out = [];
  const seen = new Set();
  for (const match of String(text).matchAll(/`([^`\n]+)`/g)) {
    const token = match[1].trim();
    if (token && !seen.has(token)) {
      seen.add(token);
      out.push(token);
    }
  }
  return out;
}

const STOPWORDS = new Set(
  'the a an and or of to in on for with is are be by at from as it its this that never always not no one ' +
    'every each when where which who what into than then so if but'.split(' '),
);

/** The word set a rule is compared on: lowercase words of three letters or more, minus stopwords. */
function wordSet(text) {
  const words = String(text)
    .toLowerCase()
    .replace(/`[^`]*`/g, ' ')
    .split(/[^a-z0-9]+/)
    .filter((w) => w.length >= 3 && !STOPWORDS.has(w));
  return new Set(words);
}

function jaccard(a, b) {
  if (a.size === 0 && b.size === 0) return 0;
  let inter = 0;
  for (const x of a) if (b.has(x)) inter += 1;
  return inter / (a.size + b.size - inter);
}

/**
 * How alike two rule bodies are, 0..1: the mean of word-set Jaccard and symbol-set Jaccard, or
 * the word measure alone when neither rule names a symbol. Two rules about the same symbols in
 * different words score high on purpose - that is the paraphrase the sentence-level duplicate
 * pass of 2026-09-06 could not see.
 */
export function similarity(bodyA, bodyB) {
  const words = jaccard(wordSet(bodyA), wordSet(bodyB));
  const symA = new Set(symbolsOf(bodyA));
  const symB = new Set(symbolsOf(bodyB));
  if (symA.size === 0 && symB.size === 0) return words;
  return (words + jaccard(symA, symB)) / 2;
}

function list(value) {
  return String(value ?? '')
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean);
}

/** A file path -> rule id: contracts/rules/<area>/<slug>.md -> <area>/<slug>. */
export function idOf(relPath) {
  const posix = relPath.replaceAll('\\', '/');
  const match = posix.match(/^contracts\/rules\/([^/]+)\/([^/]+)\.md$/);
  return match ? `${match[1]}/${match[2]}` : null;
}

/**
 * Parse one rule file. Returns { rule, problems }: a rule is returned even with problems so the
 * caller can name every fault in one run rather than the first.
 */
export function parseRule(relPath, text) {
  const problems = [];
  const id = idOf(relPath);
  if (!id) problems.push(`${relPath}: a rule lives at contracts/rules/<area>/<slug>.md`);
  const parsed = parseFrontmatter(text);
  if (!parsed) {
    problems.push(`${relPath}: no frontmatter block`);
    return { rule: null, problems };
  }
  const { data, body } = parsed;
  const rule = {
    id,
    path: relPath.replaceAll('\\', '/'),
    area: id ? id.split('/')[0] : null,
    scope: list(data.scope),
    kind: data.kind ?? '',
    fires: data.fires ?? 'contract',
    status: data.status ?? 'active',
    since: data.since ?? '',
    supersedes: list(data.supersedes),
    record: data.record ?? '',
    allowNumbers: data['allow-numbers'] === 'true',
    body: body.trim(),
    symbols: symbolsOf(body),
  };
  if (rule.scope.length === 0) problems.push(`${relPath}: scope is empty - name the globs the rule applies to, or ** for everywhere`);
  if (!KINDS.includes(rule.kind)) problems.push(`${relPath}: kind must be one of ${KINDS.join(', ')}, not "${rule.kind}"`);
  if (!STATUSES.includes(rule.status)) problems.push(`${relPath}: status must be one of ${STATUSES.join(', ')}, not "${rule.status}"`);
  if (!/^20\d\d-\d\d-\d\d$/.test(rule.since)) problems.push(`${relPath}: since must be a date (YYYY-MM-DD)`);
  if (!/^(contract|hook:[a-z0-9-]+|gate:[a-z0-9-]+|test:[^\s]+)$/.test(rule.fires)) {
    problems.push(`${relPath}: fires must be contract, hook:<name>, gate:<script> or test:<spec path>, not "${rule.fires}"`);
  }
  if (rule.body.length === 0) problems.push(`${relPath}: the rule text is empty`);
  if (rule.body.length > 600) problems.push(`${relPath}: the rule text is ${rule.body.length} characters - a rule is one to three sentences; the reasoning goes in the record`);
  problems.push(...evidenceProblems(rule.body, relPath, rule.allowNumbers));
  return { rule, problems };
}

/** The evidence patterns a rule body trips, as problem strings. */
export function evidenceProblems(body, label, allowNumbers = false) {
  const out = [];
  for (const { name, regex } of EVIDENCE_PATTERNS) {
    if (allowNumbers && name === 'a measurement') continue;
    const hit = body.match(regex);
    if (hit) out.push(`${label}: the rule text carries ${name} ("${hit[0]}") - that is evidence, and it belongs in the record`);
  }
  return out;
}

/** Where a `fires:` value says the mechanism lives, relative to the repo root. */
export function mechanismPath(fires) {
  if (fires.startsWith('hook:')) return `scripts/hooks/${fires.slice(5)}.mjs`;
  if (fires.startsWith('gate:')) return `scripts/${fires.slice(5)}.mjs`;
  if (fires.startsWith('test:')) return fires.slice(5);
  return null;
}

/** Problems that need the tree: a mechanism that does not exist, a record that does not exist. */
export function validateAgainstTree(rule, root) {
  const problems = [];
  const mechanism = mechanismPath(rule.fires);
  if (mechanism && !existsSync(path.join(root, mechanism))) {
    problems.push(`${rule.path}: fires ${rule.fires}, but ${mechanism} does not exist - land the mechanism first, or set fires: contract`);
  }
  if (rule.record && !existsSync(path.join(root, rule.record))) {
    problems.push(`${rule.path}: record ${rule.record} does not exist`);
  }
  return problems;
}

function walk(dir, out = []) {
  if (!existsSync(dir)) return out;
  for (const entry of readdirSync(dir)) {
    const full = path.join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, out);
    else if (entry.endsWith('.md')) out.push(full);
  }
  return out;
}

/** Every rule under contracts/rules, parsed and validated. */
export function loadRules(root) {
  const files = walk(path.join(root, RULES_DIR)).sort();
  const rules = [];
  const problems = [];
  for (const file of files) {
    const rel = path.relative(root, file).replaceAll('\\', '/');
    const { rule, problems: own } = parseRule(rel, readFileSync(file, 'utf8'));
    problems.push(...own);
    if (rule) {
      problems.push(...validateAgainstTree(rule, root));
      rules.push(rule);
    }
  }
  const ids = new Map();
  for (const rule of rules) {
    if (ids.has(rule.id)) problems.push(`${rule.path}: duplicate id ${rule.id}`);
    ids.set(rule.id, rule);
  }
  for (const rule of rules) {
    for (const target of rule.supersedes) {
      if (!ids.has(target)) problems.push(`${rule.path}: supersedes ${target}, which does not exist`);
      else if (ids.get(target).status !== 'retired') problems.push(`${rule.path}: supersedes ${target}, which is still active - retire it`);
    }
  }
  return { rules, problems };
}

/** Pairs of ACTIVE rules that read as the same rule. */
export function findDuplicates(rules, threshold = DUPLICATE_THRESHOLD) {
  const active = rules.filter((r) => r.status === 'active');
  const pairs = [];
  for (let i = 0; i < active.length; i += 1) {
    for (let j = i + 1; j < active.length; j += 1) {
      const score = similarity(active[i].body, active[j].body);
      if (score >= threshold) pairs.push({ a: active[i].id, b: active[j].id, score });
    }
  }
  return pairs;
}

/** The rule in `rules` most like `body`, with its score - what `learn` asks before writing. */
export function nearest(rules, body) {
  let best = null;
  for (const rule of rules) {
    if (rule.status !== 'active') continue;
    const score = similarity(rule.body, body);
    if (!best || score > best.score) best = { rule, score };
  }
  return best;
}

/** True when a mechanism carries the rule, so the compiled contract spends no bytes on it. */
export function carriedByMechanism(rule, root) {
  const mechanism = mechanismPath(rule.fires);
  return Boolean(mechanism && existsSync(path.join(root, mechanism)));
}

/** A stable file name for one scope set: the first glob's directory, plus a short hash when needed. */
export function groupSlug(scope) {
  const first = scope[0] ?? 'root';
  if (first === '**') return 'everywhere';
  const base = first
    .replace(/[*?{}[\]]+/g, '')
    .replace(/\/+$/, '')
    .replace(/\.[a-z]+$/, '')
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .toLowerCase();
  if (scope.length === 1) return base || 'root';
  let hash = 0;
  for (const ch of scope.join('|')) hash = (hash * 31 + ch.charCodeAt(0)) >>> 0;
  return `${base || 'root'}-${hash.toString(36).slice(0, 4)}`;
}

function byPriority(a, b) {
  return KIND_PRIORITY[a.kind] - KIND_PRIORITY[b.kind] || a.id.localeCompare(b.id);
}

/**
 * Render every generated file from the rules: one `.claude/rules/<group>.md` per distinct scope
 * set (paths-scoped, so it loads only when a matching file is read; a `**` scope loads at
 * launch), and the index. Returns Map<relative path, content>. Rules a mechanism carries are
 * indexed but cost the contracts nothing; retired rules appear nowhere but the index.
 */
export function compileOutputs(rules, root) {
  const outputs = new Map();
  const groups = new Map();
  for (const rule of rules) {
    if (rule.status !== 'active' || carriedByMechanism(rule, root)) continue;
    const key = [...rule.scope].sort().join('|');
    if (!groups.has(key)) groups.set(key, { scope: [...rule.scope].sort(), rules: [] });
    groups.get(key).rules.push(rule);
  }
  const slugs = new Map();
  for (const group of [...groups.values()].sort((a, b) => a.scope.join().localeCompare(b.scope.join()))) {
    let slug = groupSlug(group.scope);
    let n = 2;
    while (slugs.has(slug)) slug = `${groupSlug(group.scope)}-${n++}`;
    slugs.set(slug, group);
    const lines = [];
    const everywhere = group.scope.length === 1 && group.scope[0] === '**';
    if (!everywhere) {
      lines.push('---', 'paths:');
      for (const glob of group.scope) lines.push(`  - "${glob}"`);
      lines.push('---');
    }
    lines.push(`<!-- ${GENERATED_MARKER} from ${RULES_DIR}. Edit the rule files, then run npm run contracts:compile. -->`);
    lines.push('');
    for (const rule of group.rules.sort(byPriority)) {
      lines.push(`- **${rule.kind}** \`${rule.id}\`: ${rule.body.replace(/\s*\n\s*/g, ' ')}`);
    }
    lines.push('');
    outputs.set(`${OUTPUT_DIR}/${slug}.md`, lines.join('\n'));
  }
  outputs.set(INDEX_PATH, renderIndex(rules, root));
  return outputs;
}

function renderIndex(rules, root) {
  const lines = [
    `<!-- ${GENERATED_MARKER} from ${RULES_DIR}. Do not edit. -->`,
    '# Rule index',
    '',
    'Every rule in the store, active or retired. A rule a mechanism carries costs the loaded',
    'contracts nothing; `npm run rules -- <path>` lists what applies to a file.',
    '',
    '| id | kind | fires | status | scope | rule |',
    '|---|---|---|---|---|---|',
  ];
  for (const rule of [...rules].sort((a, b) => a.id.localeCompare(b.id))) {
    const carried = carriedByMechanism(rule, root) ? ' (carried)' : '';
    const first = rule.body.split(/(?<=[.!?])\s/)[0].replace(/\|/g, '\\|');
    lines.push(`| \`${rule.id}\` | ${rule.kind} | ${rule.fires}${carried} | ${rule.status} | ${rule.scope.map((s) => `\`${s}\``).join(', ')} | ${first} |`);
  }
  lines.push('');
  return lines.join('\n');
}

/** Which rules apply to one repo-relative path - the on-demand lookup `learn` and `rules` use. */
export function rulesFor(rules, relPath) {
  const posix = relPath.replaceAll('\\', '/');
  return rules.filter((r) => r.status === 'active' && r.scope.some((glob) => globMatches(glob, posix)));
}

/** A small glob matcher: `**` any depth, `*` within a segment, `{a,b}` alternatives. */
export function globMatches(glob, file) {
  const expanded = expandBraces(glob);
  return expanded.some((g) => toRegex(g).test(file));
}

function expandBraces(glob) {
  const match = glob.match(/\{([^{}]*)\}/);
  if (!match) return [glob];
  return match[1].split(',').flatMap((alt) => expandBraces(glob.replace(match[0], alt.trim())));
}

function toRegex(glob) {
  if (glob === '**') return /^.*$/;
  let out = '^';
  for (let i = 0; i < glob.length; i += 1) {
    const ch = glob[i];
    if (ch === '*') {
      if (glob[i + 1] === '*') {
        const slashAfter = glob[i + 2] === '/';
        out += slashAfter ? '(?:.*/)?' : '.*';
        i += slashAfter ? 2 : 1;
      } else out += '[^/]*';
    } else if (ch === '?') out += '[^/]';
    else out += ch.replace(/[.+^${}()|[\]\\]/g, '\\$&');
  }
  return new RegExp(`${out}$`);
}

/** Bytes per generated file, biggest first - the number the budget in phase 2 will bound. */
export function reportOutputs(outputs) {
  return [...outputs.entries()]
    .filter(([file]) => file.startsWith(OUTPUT_DIR))
    .map(([file, content]) => ({ file, bytes: Buffer.byteLength(content, 'utf8') }))
    .sort((a, b) => b.bytes - a.bytes);
}

export { GENERATED_MARKER };
