// The rule store behind the compiled contracts (docs/WORKFLOW_ARCHITECTURE.md §5.3).
//
// One rule per file under contracts/rules/<area>/<slug>.md, one incident per file under
// contracts/records/<area>/<date>-<slug>.md. Nothing here is loaded into a session directly:
// scripts/compile-contracts.mjs turns the active rules into the path-scoped files under
// .claude/rules/ (loaded by Claude Code only when a matching file is read) and into
// contracts/index.md. scripts/learn.mjs is the write path. This module holds what both share:
// the file format, the validation, the symbol extraction, the near-duplicate measure and the
// renderer, so the two cannot disagree about what a rule is.
//
// Rule file shape (format version 1; `v:` is read on parse so a later shape can migrate):
//
//   ---
//   v: 1
//   scope: src/components/wizard/**, src/templates/shared/base.ts
//   kind: trap            # invariant | trap | rule | taste
//   fires: contract       # contract | hook:<name> | gate:<script> | test:<spec path>
//   status: active        # active | retired
//   since: 2026-09-02
//   supersedes:           # comma-separated rule ids, optional
//   record: contracts/records/wizard/2026-09-02-inline-hidden-holder.md
//   ---
//   The rule, imperative, one to three sentences, symbols in backticks.
//
// The id is the path: <area>/<slug>. Rule text carries no dates, run ids or measurements - those
// belong in the record - because a rule that carries its own evidence is what turned the
// contracts into the 570 KB corpus measured on 2026-09-06.

import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs';
import path from 'node:path';

import { parseFrontmatter } from './owner-receipts.mjs';

export const RULES_DIR = 'contracts/rules';
export const RECORDS_DIR = 'contracts/records';
export const OUTPUT_DIR = '.claude/rules';
export const INDEX_PATH = 'contracts/index.md';
export const FORMAT_VERSION = 1;

export const KINDS = ['invariant', 'trap', 'rule', 'taste'];
const STATUSES = ['active', 'retired'];
/** Compile order inside one generated file, and the order a budget would demote from (last first). */
const KIND_PRIORITY = { invariant: 0, trap: 1, rule: 2, taste: 3 };

/**
 * Near-duplicate threshold on `similarity()`. Two active rules at or above it fail the compile:
 * one of them supersedes the other, or they are one rule. Calibrated on the empty store, so it
 * is a first guess; docs/WORKFLOW_ARCHITECTURE.md phase 2b re-measures it on the migrated corpus.
 */
export const DUPLICATE_THRESHOLD = 0.6;

/**
 * What the body of a rule may not carry. Each pattern names what it catches for the message.
 * The measurement pattern ends on a lookahead rather than `\b`, because `%` is not a word
 * character and "40% of the corpus." would otherwise pass.
 */
export const EVIDENCE_PATTERNS = [
  { name: 'a date', regex: /\b20\d\d-\d\d-\d\d\b/ },
  { name: 'a run id', regex: /\b\d{9,}\b/ },
  { name: 'a measurement', regex: /\b\d[\d,.]*\s?(bytes|KB|MB|GB|ms|min|minutes|hours|%)(?![A-Za-z])/ },
];

export const GENERATED_MARKER = 'GENERATED by scripts/compile-contracts.mjs';

/**
 * The name of a generated per-directory contract, and of its Claude counterpart.
 *
 * A migrated area keeps ONE contract file, `AGENTS.md`, generated from the store - and no sibling
 * `CLAUDE.md`, because Claude Code already loads `.claude/rules/<group>.md` when it reads a file
 * the rule scopes to. Keeping both would charge every Claude session for the same rules twice,
 * which is the cost phase 2b exists to remove.
 */
export const NESTED_CONTRACT = 'AGENTS.md';

/**
 * The per-directory `.gitattributes` a migrated area carries, and why it is not one shared file.
 *
 * Two attributes: the merge driver, so a conflict in a generated contract is settled by
 * regenerating from the merged store, and `text eol=lf`, so a Windows checkout does not report the
 * file phantom-dirty against what the compiler writes (the root `.gitattributes` explains that one
 * at length). Keeping them beside the contract rather than in the root file is the same choice the
 * rule store itself makes: two areas migrating at once then edit two different files, and the
 * shared one nobody has to conflict on stays untouched.
 */
export const NESTED_ATTRIBUTES = '.gitattributes';
export const MERGE_DRIVER = 'noacg-contracts';

/**
 * What the ALWAYS-LOADED compiled layer may cost, in bytes.
 *
 * `.claude/rules/everywhere.md` is the one generated file with no `paths:` scope, so every session
 * pays for it at launch whatever it is about to touch. Everything else is loaded only when a file
 * it scopes to is read, and is therefore not a launch cost at all. The budget is a ratchet on the
 * kernel alone: a rule that does not belong in every session's first tokens gets a scope.
 */
export const KERNEL_MAX_BYTES = 8 * 1024;
export const KERNEL_OUTPUT = `${OUTPUT_DIR}/everywhere.md`;

/** Every `` `token` `` in a text, distinct, in order of first appearance. */
export function symbolsOf(text) {
  const out = [];
  const seen = new Set();
  for (const match of String(text).matchAll(/`([^`\n]+)`/g)) {
    const token = match[1].trim();
    if (token && !seen.has(token)) {
      seen.add(token);
      out.push(token);
    }
  }
  return out;
}

const STOPWORDS = new Set(
  'the a an and or of to in on for with is are be by at from as it its this that never always not no one ' +
    'every each when where which who what into than then so if but'.split(' '),
);

/** The word set a rule is compared on: lowercase words of three letters or more, minus stopwords. */
function wordSet(text) {
  const words = String(text)
    .toLowerCase()
    .replace(/`[^`]*`/g, ' ')
    .split(/[^a-z0-9]+/)
    .filter((w) => w.length >= 3 && !STOPWORDS.has(w));
  return new Set(words);
}

function jaccard(a, b) {
  if (a.size === 0 && b.size === 0) return 0;
  let inter = 0;
  for (const x of a) if (b.has(x)) inter += 1;
  return inter / (a.size + b.size - inter);
}

/** The two sets a rule is compared on, built once per rule and reused across every pair. */
export function featuresOf(body) {
  return { words: wordSet(body), symbols: new Set(symbolsOf(body)) };
}

function similarityOfFeatures(a, b) {
  const words = jaccard(a.words, b.words);
  if (a.symbols.size === 0 && b.symbols.size === 0) return words;
  return (words + jaccard(a.symbols, b.symbols)) / 2;
}

/**
 * How alike two rule bodies are, 0..1: the mean of word-set Jaccard and symbol-set Jaccard, or
 * the word measure alone when neither rule names a symbol. Two rules about the same symbols in
 * different words score high on purpose - that is the paraphrase the sentence-level duplicate
 * pass of 2026-09-06 could not see.
 */
export function similarity(bodyA, bodyB) {
  return similarityOfFeatures(featuresOf(bodyA), featuresOf(bodyB));
}

/**
 * Split a comma list without breaking a brace group: `a/**, b/*.{ts,tsx}` is two globs, not
 * three. `globMatches` expands braces, so the two halves of the format agree.
 */
export function splitList(value) {
  const out = [];
  let depth = 0;
  let current = '';
  for (const ch of String(value ?? '')) {
    if (ch === '{') depth += 1;
    if (ch === '}') depth = Math.max(0, depth - 1);
    if (ch === ',' && depth === 0) {
      out.push(current);
      current = '';
    } else current += ch;
  }
  out.push(current);
  return out.map((s) => s.trim()).filter(Boolean);
}

/** A file path -> rule id: contracts/rules/<area>/<slug>.md -> <area>/<slug>. */
export function idOf(relPath) {
  const posix = relPath.replaceAll('\\', '/');
  const match = posix.match(/^contracts\/rules\/([^/]+)\/([^/]+)\.md$/);
  return match ? `${match[1]}/${match[2]}` : null;
}

/**
 * Parse one rule file. Returns { rule, problems }: a rule is returned even with problems so the
 * caller can name every fault in one run rather than the first. CRLF is normalised on the way
 * in, so a checkout that converts line endings reads the same as one that does not.
 */
export function parseRule(relPath, text) {
  const problems = [];
  const id = idOf(relPath);
  if (!id) problems.push(`${relPath}: a rule lives at contracts/rules/<area>/<slug>.md`);
  const parsed = parseFrontmatter(String(text).replace(/\r\n/g, '\n'));
  if (!parsed) {
    problems.push(`${relPath}: no frontmatter block`);
    return { rule: null, problems };
  }
  const { data, body } = parsed;
  const version = data.v === undefined ? FORMAT_VERSION : Number(data.v);
  if (version !== FORMAT_VERSION) {
    problems.push(`${relPath}: format version ${data.v} is not ${FORMAT_VERSION}; this build cannot read it`);
  }
  const rule = {
    v: version,
    id,
    path: relPath.replaceAll('\\', '/'),
    area: id ? id.split('/')[0] : null,
    scope: splitList(data.scope),
    kind: data.kind ?? '',
    fires: data.fires ?? 'contract',
    status: data.status ?? 'active',
    since: data.since ?? '',
    supersedes: splitList(data.supersedes),
    record: data.record ?? '',
    allowNumbers: data['allow-numbers'] === 'true',
    body: body.trim(),
    symbols: symbolsOf(body),
    features: featuresOf(body),
    carried: false,
  };
  if (rule.scope.length === 0) problems.push(`${relPath}: scope is empty - name the globs the rule applies to, or ** for everywhere`);
  if (!KINDS.includes(rule.kind)) problems.push(`${relPath}: kind must be one of ${KINDS.join(', ')}, not "${rule.kind}"`);
  if (!STATUSES.includes(rule.status)) problems.push(`${relPath}: status must be one of ${STATUSES.join(', ')}, not "${rule.status}"`);
  if (!/^20\d\d-\d\d-\d\d$/.test(rule.since)) problems.push(`${relPath}: since must be a date (YYYY-MM-DD)`);
  if (!/^(contract|hook:[a-z0-9-]+|gate:[a-z0-9-]+|test:[^\s]+)$/.test(rule.fires)) {
    problems.push(`${relPath}: fires must be contract, hook:<name>, gate:<script> or test:<spec path>, not "${rule.fires}"`);
  }
  if (rule.body.length === 0) problems.push(`${relPath}: the rule text is empty`);
  if (rule.body.length > 600) problems.push(`${relPath}: the rule text is ${rule.body.length} characters - a rule is one to three sentences; the reasoning goes in the record`);
  problems.push(...evidenceProblems(rule.body, relPath, rule.allowNumbers));
  return { rule, problems };
}

/** The evidence patterns a text trips, as problem strings. */
export function evidenceProblems(body, label, allowNumbers = false) {
  const out = [];
  for (const { name, regex } of EVIDENCE_PATTERNS) {
    if (allowNumbers && name === 'a measurement') continue;
    const hit = body.match(regex);
    if (hit) out.push(`${label}: the rule text carries ${name} ("${hit[0]}") - that is evidence, and it belongs in the record`);
  }
  return out;
}

/** Where a `fires:` value says the mechanism lives, relative to the repo root. */
export function mechanismPath(fires) {
  if (fires.startsWith('hook:')) return `scripts/hooks/${fires.slice(5)}.mjs`;
  if (fires.startsWith('gate:')) return `scripts/${fires.slice(5)}.mjs`;
  if (fires.startsWith('test:')) return fires.slice(5);
  return null;
}

/**
 * Problems that need the tree: a mechanism that does not exist, a record that does not exist.
 * Also settles `rule.carried` - whether a mechanism carries the rule, so the compiled contract
 * spends no bytes on it - once, here, rather than per use.
 */
export function validateAgainstTree(rule, root) {
  const problems = [];
  const mechanism = mechanismPath(rule.fires);
  rule.carried = Boolean(mechanism && existsSync(path.join(root, mechanism)));
  if (mechanism && !rule.carried) {
    problems.push(`${rule.path}: fires ${rule.fires}, but ${mechanism} does not exist - land the mechanism first, or set fires: contract`);
  }
  if (rule.record && !existsSync(path.join(root, rule.record))) {
    problems.push(`${rule.path}: record ${rule.record} does not exist`);
  }
  return problems;
}

function walk(dir, out = []) {
  if (!existsSync(dir)) return out;
  for (const entry of readdirSync(dir)) {
    const full = path.join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, out);
    else if (entry.endsWith('.md')) out.push(full);
  }
  return out;
}

/** Every rule under contracts/rules, parsed and validated against the tree. */
export function loadRules(root) {
  const files = walk(path.join(root, RULES_DIR)).sort();
  const rules = [];
  const problems = [];
  for (const file of files) {
    const rel = path.relative(root, file).replaceAll('\\', '/');
    const { rule, problems: own } = parseRule(rel, readFileSync(file, 'utf8'));
    problems.push(...own);
    if (rule) {
      problems.push(...validateAgainstTree(rule, root));
      rules.push(rule);
    }
  }
  const ids = new Map();
  for (const rule of rules) {
    if (ids.has(rule.id)) problems.push(`${rule.path}: duplicate id ${rule.id}`);
    ids.set(rule.id, rule);
  }
  for (const rule of rules) {
    for (const target of rule.supersedes) {
      if (!ids.has(target)) problems.push(`${rule.path}: supersedes ${target}, which does not exist`);
      else if (ids.get(target).status !== 'retired') problems.push(`${rule.path}: supersedes ${target}, which is still active - retire it`);
    }
  }
  return { rules, problems };
}

/** Pairs of ACTIVE rules that read as the same rule. Features are precomputed, so this is n^2 set work. */
export function findDuplicates(rules, threshold = DUPLICATE_THRESHOLD) {
  const active = rules.filter((r) => r.status === 'active');
  const pairs = [];
  for (let i = 0; i < active.length; i += 1) {
    for (let j = i + 1; j < active.length; j += 1) {
      const score = similarityOfFeatures(active[i].features, active[j].features);
      if (score >= threshold) pairs.push({ a: active[i].id, b: active[j].id, score });
    }
  }
  return pairs;
}

/** The rule in `rules` most like `body`, with its score - what `learn` asks before writing. */
export function nearest(rules, body) {
  const features = featuresOf(body);
  let best = null;
  for (const rule of rules) {
    if (rule.status !== 'active') continue;
    const score = similarityOfFeatures(rule.features, features);
    if (!best || score > best.score) best = { rule, score };
  }
  return best;
}

/**
 * A stable file name for one scope set: the first glob's directory, plus a short hash of the
 * whole set when there is more than one glob. The hash is what keeps the name stable when a
 * new group is added elsewhere - a counter would renumber every later file on each addition.
 */
export function groupSlug(scope) {
  const first = scope[0] ?? 'root';
  if (first === '**') return 'everywhere';
  const base = first
    .replace(/[*?{}[\]]+/g, '')
    .replace(/\/+$/, '')
    .replace(/\.[a-z]+$/, '')
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .toLowerCase();
  if (scope.length === 1) return base || 'root';
  let hash = 0;
  for (const ch of scope.join('|')) hash = (hash * 31 + ch.charCodeAt(0)) >>> 0;
  return `${base || 'root'}-${hash.toString(36).slice(0, 4)}`;
}

/**
 * The directory one glob is confined to: everything before its first wildcard, and for a plain
 * file path, the directory holding it.
 *
 *   src/templates/versus/**   -> src/templates/versus
 *   src/templates/shared/base.ts -> src/templates/shared
 *   src/components/wizard/*.tsx  -> src/components/wizard
 *   **                           -> '' (the repository root)
 */
export function globDirectory(glob) {
  const segments = glob.split('/');
  const fixed = [];
  for (const segment of segments) {
    if (/[*?{}[\]]/.test(segment)) return fixed.join('/');
    fixed.push(segment);
  }
  // No wildcard anywhere: the glob names one file, and its directory is what owns it.
  fixed.pop();
  return fixed.join('/');
}

/**
 * The one directory a rule belongs to: the deepest one containing EVERY glob in its scope.
 *
 * A rule spanning two directories has no home below their common ancestor, so it lands there -
 * and a rule whose ancestor is the repository root lands in the kernel, where the budget above
 * makes it expensive on purpose. That is the pressure that keeps a cross-cutting rule rare
 * instead of letting every area quietly widen its scope to avoid choosing.
 */
export function scopeOwner(scope) {
  const dirs = scope.map(globDirectory);
  if (dirs.length === 0) return '';
  let common = dirs[0].split('/').filter(Boolean);
  for (const dir of dirs.slice(1)) {
    const parts = dir.split('/').filter(Boolean);
    let i = 0;
    while (i < common.length && i < parts.length && common[i] === parts[i]) i += 1;
    common = common.slice(0, i);
  }
  return common.join('/');
}

function byPriority(a, b) {
  return KIND_PRIORITY[a.kind] - KIND_PRIORITY[b.kind] || a.id.localeCompare(b.id);
}

const oneLine = (text) => text.replace(/\s*\n\s*/g, ' ');

/**
 * Render every generated file from the rules: one `.claude/rules/<group>.md` per distinct scope
 * set (paths-scoped, so it loads only when a matching file is read; a `**` scope loads at
 * launch), and the index. Returns Map<relative path, content>. Rules a mechanism carries are
 * indexed but cost the contracts nothing; retired rules appear nowhere but the index.
 */
export function compileOutputs(rules, owned = new Set()) {
  const outputs = new Map();
  const groups = new Map();
  for (const rule of rules) {
    if (rule.status !== 'active' || rule.carried) continue;
    const key = [...rule.scope].sort().join('|');
    if (!groups.has(key)) groups.set(key, { scope: [...rule.scope].sort(), rules: [] });
    groups.get(key).rules.push(rule);
  }
  const taken = new Set();
  for (const group of [...groups.values()].sort((a, b) => a.scope.join().localeCompare(b.scope.join()))) {
    let slug = groupSlug(group.scope);
    for (let n = 2; taken.has(slug); n += 1) slug = `${groupSlug(group.scope)}-${n}`;
    taken.add(slug);
    const lines = [];
    const everywhere = group.scope.length === 1 && group.scope[0] === '**';
    if (!everywhere) {
      lines.push('---', 'paths:');
      for (const glob of group.scope) lines.push(`  - "${glob}"`);
      lines.push('---');
    }
    lines.push(`<!-- ${GENERATED_MARKER} from ${RULES_DIR}. Edit the rule files, then run npm run contracts:compile. -->`);
    lines.push('');
    for (const rule of group.rules.sort(byPriority)) {
      lines.push(`- **${rule.kind}** \`${rule.id}\`: ${oneLine(rule.body)}`);
    }
    lines.push('');
    outputs.set(`${OUTPUT_DIR}/${slug}.md`, lines.join('\n'));
  }
  for (const [dir, dirRules] of nestedContracts(rules, owned)) {
    // The root's files have no directory prefix; everything else is `<dir>/<name>`.
    const at = (name) => (dir === '' ? name : `${dir}/${name}`);
    outputs.set(at(NESTED_CONTRACT), renderNested(dir === '' ? '(the whole repository)' : dir, dirRules));
    if (dir !== '') outputs.set(at(NESTED_ATTRIBUTES), renderAttributes());
  }
  outputs.set(INDEX_PATH, renderIndex(rules));
  return outputs;
}

/**
 * The kernel's cost, and the problem when it is over budget.
 *
 * Separated from `compileOutputs` because the budget is a judgement about what belongs in every
 * session's first tokens, not part of rendering: a caller that only wants the files should not
 * have to care, and the number is worth printing on a green run.
 */
export function kernelBudget(outputs) {
  const bytes = Buffer.byteLength(outputs.get(KERNEL_OUTPUT) ?? '', 'utf8');
  const problems = bytes > KERNEL_MAX_BYTES
    ? [
      `${KERNEL_OUTPUT} is ${bytes} bytes against a ceiling of ${KERNEL_MAX_BYTES}. It is the one ` +
        'compiled file with no `paths:` scope, so every session pays for it before touching ' +
        'anything. Give the widest rule in it a scope, or retire it.',
    ]
    : [];
  return { bytes, max: KERNEL_MAX_BYTES, problems };
}

/**
 * Which owned directory carries which rules, deepest owner wins.
 *
 * `owned` is the set of directories whose `AGENTS.md` the compiler writes - a directory whose
 * contract is still hand-written is not in it, and its rules simply do not get a nested file yet.
 * That is what lets phase 2b migrate one area at a time: until an area's row runs, its prose is
 * still there and still says the same thing.
 */
export function nestedContracts(rules, owned) {
  const byDir = new Map();
  for (const rule of rules) {
    if (rule.status !== 'active' || rule.carried) continue;
    const home = deepestOwner(scopeOwner(rule.scope), owned);
    if (home === null) continue;
    if (!byDir.has(home)) byDir.set(home, []);
    byDir.get(home).push(rule);
  }
  return [...byDir.entries()].sort((a, b) => a[0].localeCompare(b[0]));
}

/**
 * The deepest directory in `owned` that is `dir` or an ancestor of it, or null when none is.
 *
 * Exported because the compiler's `--report` asks the same question from the other side - which
 * rules NO migrated directory owns - and two copies of this would eventually disagree about which
 * contract a rule is in.
 */
export function deepestOwner(dir, owned) {
  // THE REPOSITORY ROOT IS A DIRECTORY LIKE ANY OTHER once it carries the marker. Kernel rules -
  // the ones scoped `**` - reach Claude Code through `.claude/rules/everywhere.md`, which it loads
  // at launch; Codex reads AGENTS.md files and nothing else, so without a generated root contract
  // it would see none of them. That is the whole global rule set, including "never merge into main
  // yourself" and "publishing past main needs the user".
  if (dir === '') return owned.has('') ? '' : null;
  const parts = dir.split('/');
  for (let i = parts.length; i > 0; i -= 1) {
    const candidate = parts.slice(0, i).join('/');
    if (owned.has(candidate)) return candidate;
  }
  return null;
}

/**
 * One directory's generated contract - the file Codex reads when it works in that directory.
 *
 * There is no sibling `CLAUDE.md`: Claude Code loads the same rules from `.claude/rules/` at the
 * moment it reads a file they scope to, so a wrapper here would charge every Claude session for
 * them a second time. `scripts/check-shared-instructions.mjs` knows that and exempts a generated
 * contract from the pair rule.
 */
function renderAttributes() {
  return [
    `# ${GENERATED_MARKER}. ${NESTED_CONTRACT} here is compiled from contracts/rules.`,
    '# A conflict in it is resolved by regenerating from the merged store, never by merging text;',
    '# eol=lf keeps a Windows checkout from reading the compiler output as a modification.',
    `${NESTED_CONTRACT} merge=${MERGE_DRIVER}`,
    `${NESTED_CONTRACT} text eol=lf`,
    // ITSELF TOO. This file is written by the compiler with LF like everything else it writes, so
    // without this line it is the one generated file that reads back phantom-dirty on a Windows
    // checkout - and `check:line-endings` then fails on the very file whose job is to declare the
    // rule. It fails on every fresh worktree cut from main, not only on the branch that wrote it.
    `${NESTED_ATTRIBUTES} text eol=lf`,
    '',
  ].join('\n');
}

function renderNested(dir, rules) {
  const lines = [
    `<!-- ${GENERATED_MARKER} from ${RULES_DIR}. Edit the rule files, then run npm run contracts:compile. -->`,
    `# ${dir}`,
    '',
    // One line, because it is repeated in every migrated directory and there are a hundred of
    // them. Where to change a rule is the only thing a reader needs from this file that the rules
    // themselves do not say; the marker above already says it is generated.
    'Compiled from `contracts/rules`. Change a rule there (`npm run learn -- ...`), never here.',
    '',
  ];
  for (const rule of [...rules].sort(byPriority)) {
    lines.push(`- **${rule.kind}** \`${rule.id}\`: ${oneLine(rule.body)}`);
  }
  lines.push('');
  return lines.join('\n');
}

function renderIndex(rules) {
  const lines = [
    `<!-- ${GENERATED_MARKER} from ${RULES_DIR}. Do not edit. -->`,
    '# Rule index',
    '',
    'Every rule in the store, active or retired. A rule a mechanism carries costs the loaded',
    'contracts nothing; `npm run rules -- <path>` lists what applies to a file.',
    '',
    '| id | kind | fires | status | scope | rule |',
    '|---|---|---|---|---|---|',
  ];
  for (const rule of [...rules].sort((a, b) => a.id.localeCompare(b.id))) {
    const carried = rule.carried ? ' (carried)' : '';
    const first = oneLine(rule.body).split(/(?<=[.!?])\s/)[0].replace(/\|/g, '\\|');
    lines.push(`| \`${rule.id}\` | ${rule.kind} | ${rule.fires}${carried} | ${rule.status} | ${rule.scope.map((s) => `\`${s}\``).join(', ')} | ${first} |`);
  }
  lines.push('');
  return lines.join('\n');
}

/** Which rules apply to one repo-relative path - the on-demand lookup `learn` and `rules` use. */
export function rulesFor(rules, relPath) {
  const posix = relPath.replaceAll('\\', '/');
  return rules.filter((r) => r.status === 'active' && r.scope.some((glob) => globMatches(glob, posix)));
}

/** A small glob matcher: `**` any depth, `*` within a segment, `{a,b}` alternatives. */
export function globMatches(glob, file) {
  return expandBraces(glob).some((g) => toRegex(g).test(file));
}

function expandBraces(glob) {
  const match = glob.match(/\{([^{}]*)\}/);
  if (!match) return [glob];
  return match[1].split(',').flatMap((alt) => expandBraces(glob.replace(match[0], alt.trim())));
}

function toRegex(glob) {
  if (glob === '**') return /^.*$/;
  let out = '^';
  for (let i = 0; i < glob.length; i += 1) {
    const ch = glob[i];
    if (ch === '*') {
      if (glob[i + 1] === '*') {
        const slashAfter = glob[i + 2] === '/';
        out += slashAfter ? '(?:.*/)?' : '.*';
        i += slashAfter ? 2 : 1;
      } else out += '[^/]*';
    } else if (ch === '?') out += '[^/]';
    else out += ch.replace(/[.+^${}()|[\]\\]/g, '\\$&');
  }
  return new RegExp(`${out}$`);
}

/** Bytes per generated file, biggest first - the number a budget in phase 2 will bound. */
export function reportOutputs(outputs) {
  return [...outputs.entries()]
    .filter(([file]) => file.startsWith(OUTPUT_DIR))
    .map(([file, content]) => ({ file, bytes: Buffer.byteLength(content, 'utf8') }))
    .sort((a, b) => b.bytes - a.bytes);
}
