#!/usr/bin/env node
// The monthly instruction drift audit: what every Claude and Codex session is made to read, and
// where the instruction system is sliding back towards bloat.
//
//   npm run audit:instructions            the report
//   npm run audit:instructions -- --json  the same numbers as JSON
//
// It measures and lists; it never edits. The budgets and the ladder in contracts/README.md are the
// protection - this only notices when they are being worked around. The monthly quality review
// (area 4) runs it and does the judgement part: whether a listed line really contradicts another,
// and whether a listed workaround is still needed.
//
// The global files live outside the repository, so on a machine without them (CI, a cloud box)
// those rows read "absent" rather than failing.

import { appendFileSync, existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { KERNEL_MAX_BYTES, loadRules } from './contracts-lib.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const HOME = os.homedir();
const GLOBAL_MAX_BYTES = 2560;
const HISTORY = path.join(HOME, '.claude', 'instruction-audit-history.jsonl');

const read = (file) => (existsSync(file) ? readFileSync(file, 'utf8').replace(/\r\n/g, '\n') : null);
const bytes = (file) => (existsSync(file) ? statSync(file).size : null);
const shown = (file) => (file.startsWith(ROOT) ? path.relative(ROOT, file) : file.replace(HOME, '~'));
const dirs = (dir) => (existsSync(dir) ? readdirSync(dir, { withFileTypes: true }).filter((d) => d.isDirectory() && !d.name.startsWith('.')).map((d) => d.name) : []);

// 1. What loads before any work: the global file, the root contract, the memory index, and any
// rules file with no `paths:` scope.
const globalFile = path.join(HOME, '.codex', 'AGENTS.md');
const claudeGlobal = read(path.join(HOME, '.claude', 'CLAUDE.md'));
const memoryIndex = path.join(HOME, '.claude', 'projects', 'C--claude-NoaCG-Studio', 'memory', 'MEMORY.md');
const rulesDir = path.join(ROOT, '.claude', 'rules');
const unscopedRules = existsSync(rulesDir)
  ? readdirSync(rulesDir).filter((f) => f.endsWith('.md') && !/^---\npaths:/.test(read(path.join(rulesDir, f))))
  : [];
const always = {
  global: bytes(globalFile),
  root: bytes(path.join(ROOT, 'AGENTS.md')),
  memoryIndex: bytes(memoryIndex),
  unscopedRules: unscopedRules.length,
};

// 2. Claude and Codex drift: the Claude global file must only import the shared one, the root
// CLAUDE.md must only import the root AGENTS.md, and the two global skill folders should agree.
const drift = [];
if (claudeGlobal !== null && claudeGlobal.replace(/^#.*$/gm, '').trim() !== '@~/.codex/AGENTS.md') {
  drift.push('~/.claude/CLAUDE.md holds more than `@~/.codex/AGENTS.md` - Codex never sees the rest');
}
if (read(path.join(ROOT, 'CLAUDE.md'))?.replace(/^#.*$/gm, '').trim() !== '@AGENTS.md') {
  drift.push('the root CLAUDE.md is not just `@AGENTS.md` - the Claude CLI would miss the root rules');
}
const claudeSkills = dirs(path.join(HOME, '.claude', 'skills'));
const codexSkills = new Set([...dirs(path.join(HOME, '.agents', 'skills')), ...dirs(path.join(HOME, '.codex', 'skills'))]);
for (const name of claudeSkills.filter((n) => !codexSkills.has(n))) drift.push(`global skill \`${name}\` is Claude-only`);
for (const name of [...codexSkills].filter((n) => !claudeSkills.includes(n))) drift.push(`global skill \`${name}\` is Codex-only`);

// 3. Duplicates: one sentence of 60 characters or more written in two always-loaded or hand-written
// instruction files.
const handWritten = [];
(function walk(dir) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (['node_modules', '.git', 'dist', '.claude'].includes(entry.name)) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full);
    else if (entry.name === 'AGENTS.md' && !read(full).includes('GENERATED by scripts/compile-contracts.mjs')) handWritten.push(full);
  }
})(ROOT);
const sources = [globalFile, path.join(ROOT, 'AGENTS.md'), memoryIndex, ...handWritten].filter(existsSync);
const seen = new Map();
for (const file of sources) {
  for (const sentence of read(file).split(/(?<=[.!?])\s+/)) {
    const key = sentence.toLowerCase().replace(/[^a-z0-9 ]+/g, '').replace(/\s+/g, ' ').trim();
    if (key.length < 60) continue;
    if (!seen.has(key)) seen.set(key, new Set());
    seen.get(key).add(shown(file));
  }
}
const duplicates = [...seen.entries()].filter(([, files]) => files.size > 1).map(([key, files]) => ({ text: key.slice(0, 90), files: [...files] }));

// 4. The rule store: what is prose-only, what names a mechanism it could be carried by, and what
// talks about harness or model behaviour that may since have changed.
const { rules } = loadRules(ROOT);
const active = rules.filter((r) => r.status === 'active');
const proseOnly = active.filter((r) => r.fires === 'contract');
const couldBeMechanical = proseOnly
  .filter((r) => /`(scripts\/[\w./-]+\.mjs|e2e\/[\w./-]+\.spec\.ts|npm run check:[\w:-]+)`/.test(r.body))
  .map((r) => r.id);
// The prose instruction files a session can load or invoke: the always-loaded ones, the hand-written
// folder contracts, the workflows behind the commands, and the agent definitions.
const markdownUnder = (dir) => (existsSync(dir)
  ? readdirSync(dir, { recursive: true }).filter((f) => String(f).endsWith('.md')).map((f) => path.join(dir, String(f)))
  : []);
const proseFiles = [globalFile, path.join(ROOT, 'AGENTS.md'), ...handWritten,
  ...markdownUnder(path.join(ROOT, '.agent-workflows')), ...markdownUnder(path.join(ROOT, '.claude', 'agents'))].filter(existsSync);
// The folder-contract preamble says which tool reads the file; it names both harnesses in every
// contract and would bury the lines that matter.
const PREAMBLE = /Loaded alongside|reads it via this directory/;
const linesMatching = (regex) => proseFiles.flatMap((file) => read(file).split('\n')
  .map((line, i) => (regex.test(line) && !PREAMBLE.test(line) ? `${shown(file)}:${i + 1}` : null))
  .filter(Boolean));

const HARNESS = /\b(claude code|codex|desktop (app|pane)|older models?|classifier|permission prompts?|agent sessions?)\b/i;
const harnessWorkarounds = [
  ...active.filter((r) => HARNESS.test(r.body)).map((r) => `${r.id} (since ${r.since})`),
  ...linesMatching(HARNESS),
];

// 5. Lines that tell an agent when to ask or when to widen the task: the usual place for two rules
// to contradict each other. Listed for a reader to judge, never scored.
const ASKING = /\b(ask (the )?(owner|user)|never stop|report, don.t stop|even (if|when) unrelated|without asking)\b/i;
const askingLines = linesMatching(ASKING);

// 6. Growth since the last run.
let previous = null;
if (existsSync(HISTORY)) previous = JSON.parse(read(HISTORY).trim().split('\n').at(-1));
const snapshot = { date: new Date().toISOString().slice(0, 10), always, activeRules: active.length, proseOnly: proseOnly.length };

const report = { snapshot, previous, budgets: { global: GLOBAL_MAX_BYTES, root: KERNEL_MAX_BYTES }, drift, duplicates, couldBeMechanical, harnessWorkarounds, askingLines };
if (process.argv.includes('--json')) {
  console.log(JSON.stringify(report, null, 2));
} else {
  const delta = (now, then) => (then == null || now == null ? '' : ` (${now - then >= 0 ? '+' : ''}${now - then} since ${previous.date})`);
  const over = (value, max) => (value != null && value > max ? '  OVER BUDGET' : '');
  const show = (value) => (value == null ? 'absent' : value);
  console.log('Always loaded');
  console.log(`  global ~/.codex/AGENTS.md  ${show(always.global)} B of ${GLOBAL_MAX_BYTES}${over(always.global, GLOBAL_MAX_BYTES)}${delta(always.global, previous?.always.global)}`);
  console.log(`  root AGENTS.md             ${show(always.root)} B of ${KERNEL_MAX_BYTES}${over(always.root, KERNEL_MAX_BYTES)}${delta(always.root, previous?.always.root)}`);
  console.log(`  memory index               ${show(always.memoryIndex)} B${delta(always.memoryIndex, previous?.always.memoryIndex)}`);
  console.log(`  unscoped .claude/rules     ${always.unscopedRules}${always.unscopedRules ? '  (each loads in every Claude session)' : ''}`);
  console.log(`Rule store: ${active.length} active, ${proseOnly.length} prose-only${delta(active.length, previous?.activeRules)}`);
  const list = (title, items) => {
    console.log(`${title}: ${items.length}`);
    for (const item of items.slice(0, 25)) console.log(`  - ${typeof item === 'string' ? item : `${item.text}... in ${item.files.join(', ')}`}`);
    if (items.length > 25) console.log(`  ... and ${items.length - 25} more (--json for all)`);
  };
  list('Claude/Codex drift', drift);
  list('Duplicate sentences', duplicates);
  list('Prose rules that name a script or spec that could carry them', couldBeMechanical);
  list('Rules about harness or model behaviour - still needed?', harnessWorkarounds);
  list('Lines about asking or widening scope - check they agree', askingLines);
}
if (!process.argv.includes('--no-record') && existsSync(path.dirname(HISTORY))) appendFileSync(HISTORY, `${JSON.stringify(snapshot)}\n`);
